# ?? ??
server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MySQL
spring:
  main:
    allow-bean-definition-overriding: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # datasource
#  datasource:
#    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: cos
#    password: cos1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  # Jpa
#  jpa:
#    show-sql: true
#
#    # Hibernate
#    database: mysql
#    hibernate:
#      # ?? ?? ? create ? DB??? ???.
#      ddl-auto: update
#      # camelcase ??
#      strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    # ddl-auto ?? ?? ??
#    generate-ddl: true
#    # SQL? ?? ??
#    properties:
#      hibernate:
#        format_sql: true
#      # LazyInitializationException ??
#      enable_lazy_load_no_trans: true

    # Jpa and Hibernate for CI Test
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      
    jpa:
      show-sql: true

      database-platform: org.hibernate.dialect.H2Dialect

      hibernate:
        ddl-auto: create-drop
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

        properties:
          hibernate:
            format_sql: true

            # LazyInitializationException ??
            enable_lazy_load_no_trans: true

# spring-docs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

# jwt
jwt:
  secret:
    key: "asdasaskdljasklkjlw"



# H2 ??? ??? ?? ???
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.show-sql=true
#spring.hibernate.ddl-auto=none