# ?? ??
server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MySQL
spring:
  main:
    allow-bean-definition-overriding: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: cos
    password: cos1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jpa
  jpa:
    show-sql: true

    # Hibernate
    database: mysql
    hibernate:
      # ?? ?? ? create ? DB??? ???.
      ddl-auto: update
      # camelcase ??
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # ddl-auto ?? ?? ??
    generate-ddl: true
    # SQL? ?? ??
    properties:
      hibernate:
        format_sql: true
      # LazyInitializationException ??
      enable_lazy_load_no_trans: true

  oauth2:
    client:
      registration:
        kakao:
          client-id: 4cd45261b839373b375e0766220b3428
          redirect-uri: http:/login/auth/kakao/callback
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: account_email
          client-secret: IxXm1l2rPYcLXojdZmL9MXr8bmTkEmPQ
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me

# spring-docs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

# jwt
jwt:
  secret-key: no_asahck_no_asahck_no_asahck_no_asahck_no_asahck

# H2 ??? ??? ?? ???
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.show-sql=true
#spring.hibernate.ddl-auto=none